// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: role.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UpdateRoleData with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *UpdateRoleData) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRoleData with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in UpdateRoleDataMultiError,
// or nil if none found.
func (m *UpdateRoleData) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRoleData) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateRoleDataValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateRoleDataValidationError{
					field:  "Token",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateRoleDataValidationError{
				field:  "Token",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateRoleDataMultiError(errors)
	}
	return nil
}

// UpdateRoleDataMultiError is an error wrapping multiple validation errors
// returned by UpdateRoleData.ValidateAll() if the designated constraints
// aren't met.
type UpdateRoleDataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRoleDataMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRoleDataMultiError) AllErrors() []error { return m }

// UpdateRoleDataValidationError is the validation error returned by
// UpdateRoleData.Validate if the designated constraints aren't met.
type UpdateRoleDataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRoleDataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRoleDataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRoleDataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRoleDataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRoleDataValidationError) ErrorName() string { return "UpdateRoleDataValidationError" }

// Error satisfies the builtin error interface
func (e UpdateRoleDataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRoleData.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRoleDataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRoleDataValidationError{}

// Validate checks the field values on BusinessOwnerRole with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *BusinessOwnerRole) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BusinessOwnerRole with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// BusinessOwnerRoleMultiError, or nil if none found.
func (m *BusinessOwnerRole) ValidateAll() error {
	return m.validate(true)
}

func (m *BusinessOwnerRole) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return BusinessOwnerRoleMultiError(errors)
	}
	return nil
}

// BusinessOwnerRoleMultiError is an error wrapping multiple validation errors
// returned by BusinessOwnerRole.ValidateAll() if the designated constraints
// aren't met.
type BusinessOwnerRoleMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BusinessOwnerRoleMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BusinessOwnerRoleMultiError) AllErrors() []error { return m }

// BusinessOwnerRoleValidationError is the validation error returned by
// BusinessOwnerRole.Validate if the designated constraints aren't met.
type BusinessOwnerRoleValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BusinessOwnerRoleValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BusinessOwnerRoleValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BusinessOwnerRoleValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BusinessOwnerRoleValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BusinessOwnerRoleValidationError) ErrorName() string {
	return "BusinessOwnerRoleValidationError"
}

// Error satisfies the builtin error interface
func (e BusinessOwnerRoleValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBusinessOwnerRole.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BusinessOwnerRoleValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BusinessOwnerRoleValidationError{}
