// source: business.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var validate_validate_pb = require('./validate/validate_pb.js');
goog.object.extend(proto, validate_validate_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var phone_number_pb = require('./phone_number_pb.js');
goog.object.extend(proto, phone_number_pb);
goog.exportSymbol('proto.business.BusinessData', null, global);
goog.exportSymbol('proto.business.BusinessDataRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.business.BusinessData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.business.BusinessData.repeatedFields_, null);
};
goog.inherits(proto.business.BusinessData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.business.BusinessData.displayName = 'proto.business.BusinessData';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.business.BusinessDataRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.business.BusinessDataRequest.repeatedFields_, null);
};
goog.inherits(proto.business.BusinessDataRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.business.BusinessDataRequest.displayName = 'proto.business.BusinessDataRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.business.BusinessData.repeatedFields_ = [12];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.business.BusinessData.prototype.toObject = function(opt_includeInstance) {
  return proto.business.BusinessData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.business.BusinessData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.business.BusinessData.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: (f = msg.getType()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    businessName: (f = msg.getBusinessName()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    businessId: (f = msg.getBusinessId()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    businessEmail: (f = msg.getBusinessEmail()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    accountingEmail: (f = msg.getAccountingEmail()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    customerServiceEmail: (f = msg.getCustomerServiceEmail()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    highPriorityEmail: (f = msg.getHighPriorityEmail()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    avatarUrl: (f = msg.getAvatarUrl()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    createdOn: (f = msg.getCreatedOn()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updatedOn: (f = msg.getUpdatedOn()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    deletedOn: (f = msg.getDeletedOn()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    phoneNumbersList: jspb.Message.toObjectList(msg.getPhoneNumbersList(),
    phone_number_pb.PhoneNumberData.toObject, includeInstance),
    sk: (f = msg.getSk()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    pk: (f = msg.getPk()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.business.BusinessData}
 */
proto.business.BusinessData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.business.BusinessData;
  return proto.business.BusinessData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.business.BusinessData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.business.BusinessData}
 */
proto.business.BusinessData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setType(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setBusinessName(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setBusinessId(value);
      break;
    case 4:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setBusinessEmail(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setAccountingEmail(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setCustomerServiceEmail(value);
      break;
    case 7:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setHighPriorityEmail(value);
      break;
    case 8:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setAvatarUrl(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreatedOn(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdatedOn(value);
      break;
    case 11:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setDeletedOn(value);
      break;
    case 12:
      var value = new phone_number_pb.PhoneNumberData;
      reader.readMessage(value,phone_number_pb.PhoneNumberData.deserializeBinaryFromReader);
      msg.addPhoneNumbers(value);
      break;
    case 13:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setSk(value);
      break;
    case 14:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setPk(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.business.BusinessData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.business.BusinessData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.business.BusinessData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.business.BusinessData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getBusinessName();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getBusinessId();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getBusinessEmail();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getAccountingEmail();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCustomerServiceEmail();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getHighPriorityEmail();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getAvatarUrl();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCreatedOn();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdatedOn();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getDeletedOn();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getPhoneNumbersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      12,
      f,
      phone_number_pb.PhoneNumberData.serializeBinaryToWriter
    );
  }
  f = message.getSk();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getPk();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue type = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getType = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setType = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearType = function() {
  return this.setType(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasType = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue business_name = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getBusinessName = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setBusinessName = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearBusinessName = function() {
  return this.setBusinessName(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasBusinessName = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue business_id = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getBusinessId = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setBusinessId = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearBusinessId = function() {
  return this.setBusinessId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasBusinessId = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional google.protobuf.StringValue business_email = 4;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getBusinessEmail = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 4));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setBusinessEmail = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearBusinessEmail = function() {
  return this.setBusinessEmail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasBusinessEmail = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue accounting_email = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getAccountingEmail = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setAccountingEmail = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearAccountingEmail = function() {
  return this.setAccountingEmail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasAccountingEmail = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.StringValue customer_service_email = 6;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getCustomerServiceEmail = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 6));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setCustomerServiceEmail = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearCustomerServiceEmail = function() {
  return this.setCustomerServiceEmail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasCustomerServiceEmail = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional google.protobuf.StringValue high_priority_email = 7;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getHighPriorityEmail = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 7));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setHighPriorityEmail = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearHighPriorityEmail = function() {
  return this.setHighPriorityEmail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasHighPriorityEmail = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional google.protobuf.StringValue avatar_url = 8;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getAvatarUrl = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 8));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setAvatarUrl = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearAvatarUrl = function() {
  return this.setAvatarUrl(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasAvatarUrl = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp created_on = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.business.BusinessData.prototype.getCreatedOn = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setCreatedOn = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearCreatedOn = function() {
  return this.setCreatedOn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasCreatedOn = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp updated_on = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.business.BusinessData.prototype.getUpdatedOn = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setUpdatedOn = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearUpdatedOn = function() {
  return this.setUpdatedOn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasUpdatedOn = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional google.protobuf.Timestamp deleted_on = 11;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.business.BusinessData.prototype.getDeletedOn = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 11));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setDeletedOn = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearDeletedOn = function() {
  return this.setDeletedOn(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasDeletedOn = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * repeated PhoneNumberData phone_numbers = 12;
 * @return {!Array<!proto.business.PhoneNumberData>}
 */
proto.business.BusinessData.prototype.getPhoneNumbersList = function() {
  return /** @type{!Array<!proto.business.PhoneNumberData>} */ (
    jspb.Message.getRepeatedWrapperField(this, phone_number_pb.PhoneNumberData, 12));
};


/**
 * @param {!Array<!proto.business.PhoneNumberData>} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setPhoneNumbersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 12, value);
};


/**
 * @param {!proto.business.PhoneNumberData=} opt_value
 * @param {number=} opt_index
 * @return {!proto.business.PhoneNumberData}
 */
proto.business.BusinessData.prototype.addPhoneNumbers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 12, opt_value, proto.business.PhoneNumberData, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearPhoneNumbersList = function() {
  return this.setPhoneNumbersList([]);
};


/**
 * optional google.protobuf.StringValue SK = 13;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getSk = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 13));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setSk = function(value) {
  return jspb.Message.setWrapperField(this, 13, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearSk = function() {
  return this.setSk(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasSk = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional google.protobuf.StringValue PK = 14;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.business.BusinessData.prototype.getPk = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 14));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.business.BusinessData} returns this
*/
proto.business.BusinessData.prototype.setPk = function(value) {
  return jspb.Message.setWrapperField(this, 14, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.business.BusinessData} returns this
 */
proto.business.BusinessData.prototype.clearPk = function() {
  return this.setPk(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.business.BusinessData.prototype.hasPk = function() {
  return jspb.Message.getField(this, 14) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.business.BusinessDataRequest.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.business.BusinessDataRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.business.BusinessDataRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.business.BusinessDataRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.business.BusinessDataRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    tokenList: jspb.Message.toObjectList(msg.getTokenList(),
    google_protobuf_wrappers_pb.StringValue.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.business.BusinessDataRequest}
 */
proto.business.BusinessDataRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.business.BusinessDataRequest;
  return proto.business.BusinessDataRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.business.BusinessDataRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.business.BusinessDataRequest}
 */
proto.business.BusinessDataRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.addToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.business.BusinessDataRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.business.BusinessDataRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.business.BusinessDataRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.business.BusinessDataRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTokenList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * repeated google.protobuf.StringValue token = 1;
 * @return {!Array<!proto.google.protobuf.StringValue>}
 */
proto.business.BusinessDataRequest.prototype.getTokenList = function() {
  return /** @type{!Array<!proto.google.protobuf.StringValue>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {!Array<!proto.google.protobuf.StringValue>} value
 * @return {!proto.business.BusinessDataRequest} returns this
*/
proto.business.BusinessDataRequest.prototype.setTokenList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.protobuf.StringValue=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.protobuf.StringValue}
 */
proto.business.BusinessDataRequest.prototype.addToken = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.protobuf.StringValue, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.business.BusinessDataRequest} returns this
 */
proto.business.BusinessDataRequest.prototype.clearTokenList = function() {
  return this.setTokenList([]);
};


goog.object.extend(exports, proto.business);
