// source: carrier.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var address_pb = require('./address_pb.js');
goog.object.extend(proto, address_pb);
goog.exportSymbol('proto.carrier.Business', null, global);
goog.exportSymbol('proto.carrier.Carrier', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carrier.Carrier = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carrier.Carrier, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.carrier.Carrier.displayName = 'proto.carrier.Carrier';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carrier.Business = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carrier.Business, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.carrier.Business.displayName = 'proto.carrier.Business';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carrier.Carrier.prototype.toObject = function(opt_includeInstance) {
  return proto.carrier.Carrier.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carrier.Carrier} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.Carrier.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    authurl: jspb.Message.getFieldWithDefault(msg, 2, ""),
    rateurl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    addaddressurl: jspb.Message.getFieldWithDefault(msg, 4, ""),
    getaddressesurl: jspb.Message.getFieldWithDefault(msg, 5, ""),
    quotehistoryurl: jspb.Message.getFieldWithDefault(msg, 6, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carrier.Carrier}
 */
proto.carrier.Carrier.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carrier.Carrier;
  return proto.carrier.Carrier.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carrier.Carrier} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carrier.Carrier}
 */
proto.carrier.Carrier.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAuthurl(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setRateurl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setAddaddressurl(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setGetaddressesurl(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setQuotehistoryurl(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carrier.Carrier.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carrier.Carrier.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carrier.Carrier} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.Carrier.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAuthurl();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRateurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getAddaddressurl();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getGetaddressesurl();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getQuotehistoryurl();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * optional string Name = 1;
 * @return {string}
 */
proto.carrier.Carrier.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Carrier} returns this
 */
proto.carrier.Carrier.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string AuthUrl = 2;
 * @return {string}
 */
proto.carrier.Carrier.prototype.getAuthurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Carrier} returns this
 */
proto.carrier.Carrier.prototype.setAuthurl = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string RateUrl = 3;
 * @return {string}
 */
proto.carrier.Carrier.prototype.getRateurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Carrier} returns this
 */
proto.carrier.Carrier.prototype.setRateurl = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string AddAddressUrl = 4;
 * @return {string}
 */
proto.carrier.Carrier.prototype.getAddaddressurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Carrier} returns this
 */
proto.carrier.Carrier.prototype.setAddaddressurl = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string GetAddressesUrl = 5;
 * @return {string}
 */
proto.carrier.Carrier.prototype.getGetaddressesurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Carrier} returns this
 */
proto.carrier.Carrier.prototype.setGetaddressesurl = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string QuoteHistoryUrl = 6;
 * @return {string}
 */
proto.carrier.Carrier.prototype.getQuotehistoryurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Carrier} returns this
 */
proto.carrier.Carrier.prototype.setQuotehistoryurl = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carrier.Business.prototype.toObject = function(opt_includeInstance) {
  return proto.carrier.Business.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carrier.Business} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.Business.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, ""),
    id: jspb.Message.getFieldWithDefault(msg, 2, ""),
    orgid: jspb.Message.getFieldWithDefault(msg, 3, ""),
    sortid: jspb.Message.getFieldWithDefault(msg, 4, ""),
    businessname: jspb.Message.getFieldWithDefault(msg, 5, ""),
    legalbusinessname: jspb.Message.getFieldWithDefault(msg, 6, ""),
    businessurl: jspb.Message.getFieldWithDefault(msg, 7, ""),
    businessemail: jspb.Message.getFieldWithDefault(msg, 8, ""),
    phonenumber: jspb.Message.getFieldWithDefault(msg, 9, ""),
    createdat: jspb.Message.getFieldWithDefault(msg, 10, ""),
    updatedat: jspb.Message.getFieldWithDefault(msg, 11, ""),
    lastloginat: jspb.Message.getFieldWithDefault(msg, 12, ""),
    deletedat: jspb.Message.getFieldWithDefault(msg, 13, ""),
    businesstype: jspb.Message.getFieldWithDefault(msg, 14, ""),
    address: (f = msg.getAddress()) && address_pb.Address.toObject(includeInstance, f),
    primarycontact: jspb.Message.getFieldWithDefault(msg, 16, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carrier.Business}
 */
proto.carrier.Business.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carrier.Business;
  return proto.carrier.Business.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carrier.Business} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carrier.Business}
 */
proto.carrier.Business.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrgid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSortid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setBusinessname(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setLegalbusinessname(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setBusinessurl(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setBusinessemail(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhonenumber(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreatedat(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setUpdatedat(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setLastloginat(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeletedat(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setBusinesstype(value);
      break;
    case 15:
      var value = new address_pb.Address;
      reader.readMessage(value,address_pb.Address.deserializeBinaryFromReader);
      msg.setAddress(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setPrimarycontact(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carrier.Business.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carrier.Business.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carrier.Business} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.Business.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOrgid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getSortid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getBusinessname();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getLegalbusinessname();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getBusinessurl();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getBusinessemail();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getPhonenumber();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCreatedat();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getUpdatedat();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getLastloginat();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getDeletedat();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getBusinesstype();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getAddress();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      address_pb.Address.serializeBinaryToWriter
    );
  }
  f = message.getPrimarycontact();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
};


/**
 * optional string type = 1;
 * @return {string}
 */
proto.carrier.Business.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setType = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string id = 2;
 * @return {string}
 */
proto.carrier.Business.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string orgId = 3;
 * @return {string}
 */
proto.carrier.Business.prototype.getOrgid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setOrgid = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string sortId = 4;
 * @return {string}
 */
proto.carrier.Business.prototype.getSortid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setSortid = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string businessName = 5;
 * @return {string}
 */
proto.carrier.Business.prototype.getBusinessname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setBusinessname = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string legalBusinessName = 6;
 * @return {string}
 */
proto.carrier.Business.prototype.getLegalbusinessname = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setLegalbusinessname = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string businessUrl = 7;
 * @return {string}
 */
proto.carrier.Business.prototype.getBusinessurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setBusinessurl = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string businessEmail = 8;
 * @return {string}
 */
proto.carrier.Business.prototype.getBusinessemail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setBusinessemail = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string phoneNumber = 9;
 * @return {string}
 */
proto.carrier.Business.prototype.getPhonenumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setPhonenumber = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string createdAt = 10;
 * @return {string}
 */
proto.carrier.Business.prototype.getCreatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setCreatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string updatedAt = 11;
 * @return {string}
 */
proto.carrier.Business.prototype.getUpdatedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setUpdatedat = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string lastLoginAt = 12;
 * @return {string}
 */
proto.carrier.Business.prototype.getLastloginat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setLastloginat = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string deletedAt = 13;
 * @return {string}
 */
proto.carrier.Business.prototype.getDeletedat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setDeletedat = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string businessType = 14;
 * @return {string}
 */
proto.carrier.Business.prototype.getBusinesstype = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setBusinesstype = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional Address address = 15;
 * @return {?proto.carrier.Address}
 */
proto.carrier.Business.prototype.getAddress = function() {
  return /** @type{?proto.carrier.Address} */ (
    jspb.Message.getWrapperField(this, address_pb.Address, 15));
};


/**
 * @param {?proto.carrier.Address|undefined} value
 * @return {!proto.carrier.Business} returns this
*/
proto.carrier.Business.prototype.setAddress = function(value) {
  return jspb.Message.setWrapperField(this, 15, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.clearAddress = function() {
  return this.setAddress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.Business.prototype.hasAddress = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string primaryContact = 16;
 * @return {string}
 */
proto.carrier.Business.prototype.getPrimarycontact = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.carrier.Business} returns this
 */
proto.carrier.Business.prototype.setPrimarycontact = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


goog.object.extend(exports, proto.carrier);
