// source: quote.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var shipping_detail_pb = require('./shipping_detail_pb.js');
goog.object.extend(proto, shipping_detail_pb);
var additional_service_pb = require('./additional_service_pb.js');
goog.object.extend(proto, additional_service_pb);
var commodity_pb = require('./commodity_pb.js');
goog.object.extend(proto, commodity_pb);
var carrier_pb = require('./carrier_pb.js');
goog.object.extend(proto, carrier_pb);
var amount_pb = require('./amount_pb.js');
goog.object.extend(proto, amount_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.carrier.FetchQuotesRequest', null, global);
goog.exportSymbol('proto.carrier.ListOfQuoteResponse', null, global);
goog.exportSymbol('proto.carrier.QuoteRequest', null, global);
goog.exportSymbol('proto.carrier.QuoteResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carrier.QuoteRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.carrier.QuoteRequest.repeatedFields_, null);
};
goog.inherits(proto.carrier.QuoteRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.carrier.QuoteRequest.displayName = 'proto.carrier.QuoteRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carrier.QuoteResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carrier.QuoteResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.carrier.QuoteResponse.displayName = 'proto.carrier.QuoteResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carrier.ListOfQuoteResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.carrier.ListOfQuoteResponse.repeatedFields_, null);
};
goog.inherits(proto.carrier.ListOfQuoteResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.carrier.ListOfQuoteResponse.displayName = 'proto.carrier.ListOfQuoteResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carrier.FetchQuotesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carrier.FetchQuotesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.carrier.FetchQuotesRequest.displayName = 'proto.carrier.FetchQuotesRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.carrier.QuoteRequest.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carrier.QuoteRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.carrier.QuoteRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carrier.QuoteRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.QuoteRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    quoteid: (f = msg.getQuoteid()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    mode: (f = msg.getMode()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    liablepartyid: (f = msg.getLiablepartyid()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    shippingdetail: (f = msg.getShippingdetail()) && shipping_detail_pb.ShippingDetail.toObject(includeInstance, f),
    additionalservicesList: (f = jspb.Message.getRepeatedField(msg, 5)) == null ? undefined : f,
    commoditiesList: jspb.Message.toObjectList(msg.getCommoditiesList(),
    commodity_pb.Commodity.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carrier.QuoteRequest}
 */
proto.carrier.QuoteRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carrier.QuoteRequest;
  return proto.carrier.QuoteRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carrier.QuoteRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carrier.QuoteRequest}
 */
proto.carrier.QuoteRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setQuoteid(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setMode(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setLiablepartyid(value);
      break;
    case 4:
      var value = new shipping_detail_pb.ShippingDetail;
      reader.readMessage(value,shipping_detail_pb.ShippingDetail.deserializeBinaryFromReader);
      msg.setShippingdetail(value);
      break;
    case 5:
      var values = /** @type {!Array<!proto.carrier.AdditionalService>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addAdditionalservices(values[i]);
      }
      break;
    case 6:
      var value = new commodity_pb.Commodity;
      reader.readMessage(value,commodity_pb.Commodity.deserializeBinaryFromReader);
      msg.addCommodities(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carrier.QuoteRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carrier.QuoteRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carrier.QuoteRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.QuoteRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuoteid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getMode();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getLiablepartyid();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getShippingdetail();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      shipping_detail_pb.ShippingDetail.serializeBinaryToWriter
    );
  }
  f = message.getAdditionalservicesList();
  if (f.length > 0) {
    writer.writePackedEnum(
      5,
      f
    );
  }
  f = message.getCommoditiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      commodity_pb.Commodity.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue quoteId = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.QuoteRequest.prototype.getQuoteid = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.QuoteRequest} returns this
*/
proto.carrier.QuoteRequest.prototype.setQuoteid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.clearQuoteid = function() {
  return this.setQuoteid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteRequest.prototype.hasQuoteid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue mode = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.QuoteRequest.prototype.getMode = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.QuoteRequest} returns this
*/
proto.carrier.QuoteRequest.prototype.setMode = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.clearMode = function() {
  return this.setMode(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteRequest.prototype.hasMode = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue liablePartyID = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.QuoteRequest.prototype.getLiablepartyid = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.QuoteRequest} returns this
*/
proto.carrier.QuoteRequest.prototype.setLiablepartyid = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.clearLiablepartyid = function() {
  return this.setLiablepartyid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteRequest.prototype.hasLiablepartyid = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional ShippingDetail shippingDetail = 4;
 * @return {?proto.carrier.ShippingDetail}
 */
proto.carrier.QuoteRequest.prototype.getShippingdetail = function() {
  return /** @type{?proto.carrier.ShippingDetail} */ (
    jspb.Message.getWrapperField(this, shipping_detail_pb.ShippingDetail, 4));
};


/**
 * @param {?proto.carrier.ShippingDetail|undefined} value
 * @return {!proto.carrier.QuoteRequest} returns this
*/
proto.carrier.QuoteRequest.prototype.setShippingdetail = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.clearShippingdetail = function() {
  return this.setShippingdetail(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteRequest.prototype.hasShippingdetail = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * repeated AdditionalService additionalServices = 5;
 * @return {!Array<!proto.carrier.AdditionalService>}
 */
proto.carrier.QuoteRequest.prototype.getAdditionalservicesList = function() {
  return /** @type {!Array<!proto.carrier.AdditionalService>} */ (jspb.Message.getRepeatedField(this, 5));
};


/**
 * @param {!Array<!proto.carrier.AdditionalService>} value
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.setAdditionalservicesList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {!proto.carrier.AdditionalService} value
 * @param {number=} opt_index
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.addAdditionalservices = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.clearAdditionalservicesList = function() {
  return this.setAdditionalservicesList([]);
};


/**
 * repeated Commodity commodities = 6;
 * @return {!Array<!proto.carrier.Commodity>}
 */
proto.carrier.QuoteRequest.prototype.getCommoditiesList = function() {
  return /** @type{!Array<!proto.carrier.Commodity>} */ (
    jspb.Message.getRepeatedWrapperField(this, commodity_pb.Commodity, 6));
};


/**
 * @param {!Array<!proto.carrier.Commodity>} value
 * @return {!proto.carrier.QuoteRequest} returns this
*/
proto.carrier.QuoteRequest.prototype.setCommoditiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.carrier.Commodity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.carrier.Commodity}
 */
proto.carrier.QuoteRequest.prototype.addCommodities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.carrier.Commodity, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.carrier.QuoteRequest} returns this
 */
proto.carrier.QuoteRequest.prototype.clearCommoditiesList = function() {
  return this.setCommoditiesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carrier.QuoteResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.carrier.QuoteResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carrier.QuoteResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.QuoteResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    quoteid: (f = msg.getQuoteid()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    sortid: (f = msg.getSortid()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    carrier: (f = msg.getCarrier()) && carrier_pb.Carrier.toObject(includeInstance, f),
    amount: (f = msg.getAmount()) && amount_pb.Amount.toObject(includeInstance, f),
    transittime: (f = msg.getTransittime()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    guranteed: (f = msg.getGuranteed()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carrier.QuoteResponse}
 */
proto.carrier.QuoteResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carrier.QuoteResponse;
  return proto.carrier.QuoteResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carrier.QuoteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carrier.QuoteResponse}
 */
proto.carrier.QuoteResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setQuoteid(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setSortid(value);
      break;
    case 3:
      var value = new carrier_pb.Carrier;
      reader.readMessage(value,carrier_pb.Carrier.deserializeBinaryFromReader);
      msg.setCarrier(value);
      break;
    case 4:
      var value = new amount_pb.Amount;
      reader.readMessage(value,amount_pb.Amount.deserializeBinaryFromReader);
      msg.setAmount(value);
      break;
    case 5:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setTransittime(value);
      break;
    case 6:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setGuranteed(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carrier.QuoteResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carrier.QuoteResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carrier.QuoteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.QuoteResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuoteid();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getSortid();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getCarrier();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      carrier_pb.Carrier.serializeBinaryToWriter
    );
  }
  f = message.getAmount();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      amount_pb.Amount.serializeBinaryToWriter
    );
  }
  f = message.getTransittime();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getGuranteed();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue quoteId = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.QuoteResponse.prototype.getQuoteid = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.QuoteResponse} returns this
*/
proto.carrier.QuoteResponse.prototype.setQuoteid = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteResponse} returns this
 */
proto.carrier.QuoteResponse.prototype.clearQuoteid = function() {
  return this.setQuoteid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteResponse.prototype.hasQuoteid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue sortId = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.QuoteResponse.prototype.getSortid = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.QuoteResponse} returns this
*/
proto.carrier.QuoteResponse.prototype.setSortid = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteResponse} returns this
 */
proto.carrier.QuoteResponse.prototype.clearSortid = function() {
  return this.setSortid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteResponse.prototype.hasSortid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Carrier carrier = 3;
 * @return {?proto.carrier.Carrier}
 */
proto.carrier.QuoteResponse.prototype.getCarrier = function() {
  return /** @type{?proto.carrier.Carrier} */ (
    jspb.Message.getWrapperField(this, carrier_pb.Carrier, 3));
};


/**
 * @param {?proto.carrier.Carrier|undefined} value
 * @return {!proto.carrier.QuoteResponse} returns this
*/
proto.carrier.QuoteResponse.prototype.setCarrier = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteResponse} returns this
 */
proto.carrier.QuoteResponse.prototype.clearCarrier = function() {
  return this.setCarrier(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteResponse.prototype.hasCarrier = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Amount amount = 4;
 * @return {?proto.carrier.Amount}
 */
proto.carrier.QuoteResponse.prototype.getAmount = function() {
  return /** @type{?proto.carrier.Amount} */ (
    jspb.Message.getWrapperField(this, amount_pb.Amount, 4));
};


/**
 * @param {?proto.carrier.Amount|undefined} value
 * @return {!proto.carrier.QuoteResponse} returns this
*/
proto.carrier.QuoteResponse.prototype.setAmount = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteResponse} returns this
 */
proto.carrier.QuoteResponse.prototype.clearAmount = function() {
  return this.setAmount(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteResponse.prototype.hasAmount = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional google.protobuf.StringValue transitTime = 5;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.QuoteResponse.prototype.getTransittime = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 5));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.QuoteResponse} returns this
*/
proto.carrier.QuoteResponse.prototype.setTransittime = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteResponse} returns this
 */
proto.carrier.QuoteResponse.prototype.clearTransittime = function() {
  return this.setTransittime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteResponse.prototype.hasTransittime = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional google.protobuf.BoolValue guranteed = 6;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.carrier.QuoteResponse.prototype.getGuranteed = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 6));
};


/**
 * @param {?proto.google.protobuf.BoolValue|undefined} value
 * @return {!proto.carrier.QuoteResponse} returns this
*/
proto.carrier.QuoteResponse.prototype.setGuranteed = function(value) {
  return jspb.Message.setWrapperField(this, 6, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.QuoteResponse} returns this
 */
proto.carrier.QuoteResponse.prototype.clearGuranteed = function() {
  return this.setGuranteed(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.QuoteResponse.prototype.hasGuranteed = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.carrier.ListOfQuoteResponse.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carrier.ListOfQuoteResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.carrier.ListOfQuoteResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carrier.ListOfQuoteResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.ListOfQuoteResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    quote: (f = msg.getQuote()) && proto.carrier.QuoteRequest.toObject(includeInstance, f),
    quotesList: jspb.Message.toObjectList(msg.getQuotesList(),
    proto.carrier.QuoteResponse.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carrier.ListOfQuoteResponse}
 */
proto.carrier.ListOfQuoteResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carrier.ListOfQuoteResponse;
  return proto.carrier.ListOfQuoteResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carrier.ListOfQuoteResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carrier.ListOfQuoteResponse}
 */
proto.carrier.ListOfQuoteResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.carrier.QuoteRequest;
      reader.readMessage(value,proto.carrier.QuoteRequest.deserializeBinaryFromReader);
      msg.setQuote(value);
      break;
    case 2:
      var value = new proto.carrier.QuoteResponse;
      reader.readMessage(value,proto.carrier.QuoteResponse.deserializeBinaryFromReader);
      msg.addQuotes(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carrier.ListOfQuoteResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carrier.ListOfQuoteResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carrier.ListOfQuoteResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.ListOfQuoteResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getQuote();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.carrier.QuoteRequest.serializeBinaryToWriter
    );
  }
  f = message.getQuotesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.carrier.QuoteResponse.serializeBinaryToWriter
    );
  }
};


/**
 * optional QuoteRequest quote = 1;
 * @return {?proto.carrier.QuoteRequest}
 */
proto.carrier.ListOfQuoteResponse.prototype.getQuote = function() {
  return /** @type{?proto.carrier.QuoteRequest} */ (
    jspb.Message.getWrapperField(this, proto.carrier.QuoteRequest, 1));
};


/**
 * @param {?proto.carrier.QuoteRequest|undefined} value
 * @return {!proto.carrier.ListOfQuoteResponse} returns this
*/
proto.carrier.ListOfQuoteResponse.prototype.setQuote = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.ListOfQuoteResponse} returns this
 */
proto.carrier.ListOfQuoteResponse.prototype.clearQuote = function() {
  return this.setQuote(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.ListOfQuoteResponse.prototype.hasQuote = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated QuoteResponse quotes = 2;
 * @return {!Array<!proto.carrier.QuoteResponse>}
 */
proto.carrier.ListOfQuoteResponse.prototype.getQuotesList = function() {
  return /** @type{!Array<!proto.carrier.QuoteResponse>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.carrier.QuoteResponse, 2));
};


/**
 * @param {!Array<!proto.carrier.QuoteResponse>} value
 * @return {!proto.carrier.ListOfQuoteResponse} returns this
*/
proto.carrier.ListOfQuoteResponse.prototype.setQuotesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.carrier.QuoteResponse=} opt_value
 * @param {number=} opt_index
 * @return {!proto.carrier.QuoteResponse}
 */
proto.carrier.ListOfQuoteResponse.prototype.addQuotes = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.carrier.QuoteResponse, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.carrier.ListOfQuoteResponse} returns this
 */
proto.carrier.ListOfQuoteResponse.prototype.clearQuotesList = function() {
  return this.setQuotesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carrier.FetchQuotesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.carrier.FetchQuotesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carrier.FetchQuotesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.FetchQuotesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    startfrom: (f = msg.getStartfrom()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    endon: (f = msg.getEndon()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f),
    orgid: (f = msg.getOrgid()) && google_protobuf_wrappers_pb.StringValue.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carrier.FetchQuotesRequest}
 */
proto.carrier.FetchQuotesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carrier.FetchQuotesRequest;
  return proto.carrier.FetchQuotesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carrier.FetchQuotesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carrier.FetchQuotesRequest}
 */
proto.carrier.FetchQuotesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setStartfrom(value);
      break;
    case 2:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setEndon(value);
      break;
    case 3:
      var value = new google_protobuf_wrappers_pb.StringValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.StringValue.deserializeBinaryFromReader);
      msg.setOrgid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carrier.FetchQuotesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carrier.FetchQuotesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carrier.FetchQuotesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.FetchQuotesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStartfrom();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getEndon();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
  f = message.getOrgid();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      google_protobuf_wrappers_pb.StringValue.serializeBinaryToWriter
    );
  }
};


/**
 * optional google.protobuf.StringValue startFrom = 1;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.FetchQuotesRequest.prototype.getStartfrom = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 1));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.FetchQuotesRequest} returns this
*/
proto.carrier.FetchQuotesRequest.prototype.setStartfrom = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.FetchQuotesRequest} returns this
 */
proto.carrier.FetchQuotesRequest.prototype.clearStartfrom = function() {
  return this.setStartfrom(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.FetchQuotesRequest.prototype.hasStartfrom = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional google.protobuf.StringValue endOn = 2;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.FetchQuotesRequest.prototype.getEndon = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 2));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.FetchQuotesRequest} returns this
*/
proto.carrier.FetchQuotesRequest.prototype.setEndon = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.FetchQuotesRequest} returns this
 */
proto.carrier.FetchQuotesRequest.prototype.clearEndon = function() {
  return this.setEndon(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.FetchQuotesRequest.prototype.hasEndon = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional google.protobuf.StringValue orgId = 3;
 * @return {?proto.google.protobuf.StringValue}
 */
proto.carrier.FetchQuotesRequest.prototype.getOrgid = function() {
  return /** @type{?proto.google.protobuf.StringValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.StringValue, 3));
};


/**
 * @param {?proto.google.protobuf.StringValue|undefined} value
 * @return {!proto.carrier.FetchQuotesRequest} returns this
*/
proto.carrier.FetchQuotesRequest.prototype.setOrgid = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.FetchQuotesRequest} returns this
 */
proto.carrier.FetchQuotesRequest.prototype.clearOrgid = function() {
  return this.setOrgid(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.FetchQuotesRequest.prototype.hasOrgid = function() {
  return jspb.Message.getField(this, 3) != null;
};


goog.object.extend(exports, proto.carrier);
