// source: shipping_detail.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var pickup_pb = require('./pickup_pb.js');
goog.object.extend(proto, pickup_pb);
var delivery_pb = require('./delivery_pb.js');
goog.object.extend(proto, delivery_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
goog.exportSymbol('proto.carrier.ShippingDetail', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.carrier.ShippingDetail = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.carrier.ShippingDetail, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.carrier.ShippingDetail.displayName = 'proto.carrier.ShippingDetail';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.carrier.ShippingDetail.prototype.toObject = function(opt_includeInstance) {
  return proto.carrier.ShippingDetail.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.carrier.ShippingDetail} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.ShippingDetail.toObject = function(includeInstance, msg) {
  var f, obj = {
    pickup: (f = msg.getPickup()) && pickup_pb.Pickup.toObject(includeInstance, f),
    delivery: (f = msg.getDelivery()) && delivery_pb.Delivery.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.carrier.ShippingDetail}
 */
proto.carrier.ShippingDetail.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.carrier.ShippingDetail;
  return proto.carrier.ShippingDetail.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.carrier.ShippingDetail} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.carrier.ShippingDetail}
 */
proto.carrier.ShippingDetail.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new pickup_pb.Pickup;
      reader.readMessage(value,pickup_pb.Pickup.deserializeBinaryFromReader);
      msg.setPickup(value);
      break;
    case 2:
      var value = new delivery_pb.Delivery;
      reader.readMessage(value,delivery_pb.Delivery.deserializeBinaryFromReader);
      msg.setDelivery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.carrier.ShippingDetail.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.carrier.ShippingDetail.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.carrier.ShippingDetail} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.carrier.ShippingDetail.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPickup();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      pickup_pb.Pickup.serializeBinaryToWriter
    );
  }
  f = message.getDelivery();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      delivery_pb.Delivery.serializeBinaryToWriter
    );
  }
};


/**
 * optional Pickup pickup = 1;
 * @return {?proto.carrier.Pickup}
 */
proto.carrier.ShippingDetail.prototype.getPickup = function() {
  return /** @type{?proto.carrier.Pickup} */ (
    jspb.Message.getWrapperField(this, pickup_pb.Pickup, 1));
};


/**
 * @param {?proto.carrier.Pickup|undefined} value
 * @return {!proto.carrier.ShippingDetail} returns this
*/
proto.carrier.ShippingDetail.prototype.setPickup = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.ShippingDetail} returns this
 */
proto.carrier.ShippingDetail.prototype.clearPickup = function() {
  return this.setPickup(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.ShippingDetail.prototype.hasPickup = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Delivery delivery = 2;
 * @return {?proto.carrier.Delivery}
 */
proto.carrier.ShippingDetail.prototype.getDelivery = function() {
  return /** @type{?proto.carrier.Delivery} */ (
    jspb.Message.getWrapperField(this, delivery_pb.Delivery, 2));
};


/**
 * @param {?proto.carrier.Delivery|undefined} value
 * @return {!proto.carrier.ShippingDetail} returns this
*/
proto.carrier.ShippingDetail.prototype.setDelivery = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.carrier.ShippingDetail} returns this
 */
proto.carrier.ShippingDetail.prototype.clearDelivery = function() {
  return this.setDelivery(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.carrier.ShippingDetail.prototype.hasDelivery = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.carrier);
